import '../models/brand.dart';
import '../models/category.dart';
import '../models/product.dart';
import '../models/supplier.dart';
import '../models/customer.dart';
import '../models/loyalty_card.dart';

// Реальные бренды; ассортимент, цены, остатки и контрагенты — учебные данные.
const seedBrands = [
  Brand(
    id: 1,
    name: 'Bioderma',
    country: 'Франция',
    foundedYear: 1977,
    description: 'Дерматологический уход за лицом и телом. Линейки Sensibio, Hydrabio и Atoderm.',
  ),
  Brand(
    id: 2,
    name: 'Garnier',
    country: 'Франция',
    foundedYear: 1904,
    description:
        'Средства для ухода за кожей и волосами, мицеллярная вода и маски.',
  ),
  Brand(
    id: 3,
    name: 'COSRX',
    country: 'Южная Корея',
    foundedYear: 2013,
    description:
        'Корейский бренд ухода за кожей: очищение, сыворотки и увлажнение.',
  ),
  Brand(
    id: 4,
    name: 'Maybelline New York',
    country: 'США',
    foundedYear: 1915,
    description:
        'Декоративная косметика: тушь, тональные средства, помады и тени.',
  ),
  Brand(
    id: 5,
    name: 'NIVEA',
    country: 'Германия',
    foundedYear: 1911,
    description: 'Повседневный уход за лицом, телом и руками.',
  ),
  Brand(
    id: 6,
    name: 'L’Oréal Paris',
    country: 'Франция',
    foundedYear: 1909,
    description: 'Косметика для макияжа, ухода за кожей и волосами.',
  ),
  Brand(
    id: 7,
    name: 'CeraVe',
    country: 'США',
    foundedYear: 2005,
    description: 'Очищающие и увлажняющие средства для лица и тела.',
  ),
  Brand(
    id: 8,
    name: 'La Roche-Posay',
    country: 'Франция',
    foundedYear: 1975,
    description: 'Дерматологическая косметика: Toleriane, Lipikar и Anthelios.',
  ),
];
const seedCategories = [
  Category(1, 'Уход за лицом'),
  Category(2, 'Макияж'),
  Category(3, 'Уход за телом'),
  Category(4, 'Уход за волосами'),
  Category(5, 'Защита от солнца'),
];

final List<Product> seedProducts = List.unmodifiable([
  Product(
    id: 1,
    name: 'Увлажняющий крем для лица',
    sku: 'COS-0001',
    brandId: 1,
    supplierId: 1,
    categoryId: 1,
    priceKopecks: 189000,
    stock: 24,
    volume: '50 мл',
    description: 'Лёгкая текстура для ежедневного ухода за кожей.',
  ),
  Product(
    id: 2,
    name: 'Сыворотка с гиалуроновой кислотой',
    sku: 'COS-0002',
    brandId: 3,
    supplierId: 3,
    categoryId: 1,
    priceKopecks: 159000,
    stock: 18,
    volume: '30 мл',
    description: 'Увлажняющая сыворотка для утреннего и вечернего ухода.',
  ),
  Product(
    id: 3,
    name: 'Очищающая пенка',
    sku: 'COS-0003',
    brandId: 7,
    supplierId: 1,
    categoryId: 1,
    priceKopecks: 89000,
    stock: 32,
    volume: '150 мл',
    description: 'Нежная пенка для ежедневного очищения лица.',
  ),
  Product(
    id: 4,
    name: 'Тоник с розовой водой',
    sku: 'COS-0004',
    brandId: 2,
    supplierId: 2,
    categoryId: 1,
    priceKopecks: 65000,
    stock: 40,
    volume: '200 мл',
    description: 'Освежающий тоник с мягким цветочным ароматом.',
  ),
  Product(
    id: 5,
    name: 'Питательный ночной крем',
    sku: 'COS-0005',
    brandId: 5,
    supplierId: 2,
    categoryId: 1,
    priceKopecks: 219000,
    stock: 12,
    volume: '50 мл',
    description: 'Насыщенная текстура для вечернего ухода.',
  ),
  Product(
    id: 6,
    name: 'Тканевая маска с алоэ',
    sku: 'COS-0006',
    brandId: 2,
    supplierId: 2,
    categoryId: 1,
    priceKopecks: 19000,
    stock: 65,
    volume: '25 мл',
    description: 'Одноразовая маска для увлажняющего ухода.',
  ),
  Product(
    id: 7,
    name: 'Мицеллярная вода Sensibio H2O',
    sku: 'COS-0007',
    brandId: 1,
    supplierId: 1,
    categoryId: 1,
    priceKopecks: 72000,
    stock: 28,
    volume: '250 мл',
    description: 'Средство для снятия повседневного макияжа.',
  ),
  Product(
    id: 8,
    name: 'Крем для кожи вокруг глаз',
    sku: 'COS-0008',
    brandId: 1,
    supplierId: 1,
    categoryId: 1,
    priceKopecks: 169000,
    stock: 15,
    volume: '15 мл',
    description: 'Лёгкий крем для деликатной зоны вокруг глаз.',
  ),
  Product(
    id: 9,
    name: 'Матовая помада «Пыльная роза»',
    sku: 'COS-0009',
    brandId: 4,
    supplierId: 2,
    categoryId: 2,
    priceKopecks: 99000,
    stock: 21,
    volume: '4 г',
    description: 'Приглушённый розовый оттенок с матовым финишем.',
  ),
  Product(
    id: 10,
    name: 'Тушь для ресниц',
    sku: 'COS-0010',
    brandId: 4,
    supplierId: 2,
    categoryId: 2,
    priceKopecks: 119000,
    stock: 17,
    volume: '10 мл',
    description: 'Классическая чёрная тушь с удобной щёточкой.',
  ),
  Product(
    id: 11,
    name: 'Тональный флюид',
    sku: 'COS-0011',
    brandId: 4,
    supplierId: 2,
    categoryId: 2,
    priceKopecks: 249000,
    stock: 8,
    volume: '30 мл',
    description: 'Лёгкое покрытие с естественным финишем.',
  ),
  Product(
    id: 12,
    name: 'Кремовые румяна «Персик»',
    sku: 'COS-0012',
    brandId: 4,
    supplierId: 2,
    categoryId: 2,
    priceKopecks: 85000,
    stock: 25,
    volume: '6 г',
    description: 'Персиковый оттенок с кремовой текстурой.',
  ),
  Product(
    id: 13,
    name: 'Прозрачный гель для бровей',
    sku: 'COS-0013',
    brandId: 4,
    supplierId: 2,
    categoryId: 2,
    priceKopecks: 59000,
    stock: 34,
    volume: '7 мл',
    description: 'Прозрачный гель для укладки бровей.',
  ),
  Product(
    id: 14,
    name: 'Блеск для губ',
    sku: 'COS-0014',
    brandId: 4,
    supplierId: 2,
    categoryId: 2,
    priceKopecks: 69000,
    stock: 0,
    volume: '5 мл',
    description: 'Полупрозрачный блеск с сияющим финишем.',
  ),
  Product(
    id: 15,
    name: 'Гель для душа «Вербена»',
    sku: 'COS-0015',
    brandId: 5,
    supplierId: 2,
    categoryId: 3,
    priceKopecks: 49000,
    stock: 45,
    volume: '300 мл',
    description: 'Мягкий гель с освежающим травяным ароматом.',
  ),
  Product(
    id: 16,
    name: 'Крем для рук',
    sku: 'COS-0016',
    brandId: 5,
    supplierId: 2,
    categoryId: 3,
    priceKopecks: 39000,
    stock: 52,
    volume: '75 мл',
    description: 'Компактный крем для повседневного ухода.',
  ),
  Product(
    id: 17,
    name: 'Масло для душа Atoderm',
    sku: 'COS-0017',
    brandId: 1,
    supplierId: 1,
    categoryId: 3,
    priceKopecks: 179000,
    stock: 14,
    volume: '100 мл',
    description: 'Очищающее масло для ухода за кожей тела.',
  ),
  Product(
    id: 18,
    name: 'Скраб для тела',
    sku: 'COS-0018',
    brandId: 2,
    supplierId: 2,
    categoryId: 3,
    priceKopecks: 79000,
    stock: 19,
    volume: '250 г',
    description: 'Скраб с сахарными частицами и масляной основой.',
  ),
  Product(
    id: 19,
    name: 'Лосьон для тела',
    sku: 'COS-0019',
    brandId: 7,
    supplierId: 1,
    categoryId: 3,
    priceKopecks: 95000,
    stock: 23,
    volume: '250 мл',
    description: 'Лёгкий лосьон с нейтральным ароматом.',
  ),
  Product(
    id: 20,
    name: 'Увлажняющий шампунь',
    sku: 'COS-0020',
    brandId: 6,
    supplierId: 2,
    categoryId: 4,
    priceKopecks: 109000,
    stock: 30,
    volume: '300 мл',
    description: 'Шампунь для регулярного ухода за волосами.',
  ),
  Product(
    id: 21,
    name: 'Восстанавливающая маска для волос',
    sku: 'COS-0021',
    brandId: 6,
    supplierId: 2,
    categoryId: 4,
    priceKopecks: 139000,
    stock: 16,
    volume: '200 мл',
    description: 'Густая маска для ухода по длине волос.',
  ),
  Product(
    id: 22,
    name: 'Кондиционер для волос',
    sku: 'COS-0022',
    brandId: 2,
    supplierId: 2,
    categoryId: 4,
    priceKopecks: 69000,
    stock: 27,
    volume: '250 мл',
    description: 'Кондиционер для мягкости и лёгкого расчёсывания.',
  ),
  Product(
    id: 23,
    name: 'Солнцезащитный крем SPF 50',
    sku: 'COS-0023',
    brandId: 8,
    supplierId: 1,
    categoryId: 5,
    priceKopecks: 149000,
    stock: 22,
    volume: '50 мл',
    description: 'Демонстрационный товар из категории защиты от солнца.',
  ),
  Product(
    id: 24,
    name: 'Солнцезащитный флюид SPF 30',
    sku: 'COS-0024',
    brandId: 8,
    supplierId: 1,
    categoryId: 5,
    priceKopecks: 129000,
    stock: 11,
    volume: '50 мл',
    description: 'Лёгкая текстура для ежедневного ухода.',
  ),
  Product(
    id: 25,
    name: 'Бальзам для губ SPF 15',
    sku: 'COS-0025',
    brandId: 5,
    supplierId: 2,
    categoryId: 5,
    priceKopecks: 45000,
    stock: 38,
    volume: '4 г',
    description: 'Компактный бальзам для ухода за губами.',
  ),
  Product(
    id: 26,
    name: 'Гель для умывания Low pH',
    sku: 'COS-0026',
    brandId: 3,
    supplierId: 3,
    categoryId: 1,
    priceKopecks: 125000,
    stock: 13,
    volume: '150 мл',
    description: 'Гель для ежедневного очищения лица.',
  ),
  Product(
    id: 27,
    name: 'Палетка теней «Нюд»',
    sku: 'COS-0027',
    brandId: 4,
    supplierId: 2,
    categoryId: 2,
    priceKopecks: 189000,
    stock: 9,
    volume: '12 г',
    description: 'Шесть нейтральных оттенков для повседневного макияжа.',
  ),
  Product(
    id: 28,
    name: 'Несмываемый крем для волос',
    sku: 'COS-0028',
    brandId: 6,
    supplierId: 2,
    categoryId: 4,
    priceKopecks: 119000,
    stock: 20,
    volume: '150 мл',
    description: 'Завершающий этап ухода за длиной волос.',
  ),
  Product(
    id: 29,
    name: 'Бальзам для тела',
    sku: 'COS-0029',
    brandId: 5,
    supplierId: 2,
    categoryId: 3,
    priceKopecks: 159000,
    stock: 7,
    volume: '200 мл',
    description: 'Плотный бальзам с мягким ненавязчивым ароматом.',
  ),
  Product(
    id: 30,
    name: 'Гидрофильное масло',
    sku: 'COS-0030',
    brandId: 3,
    supplierId: 3,
    categoryId: 1,
    priceKopecks: 145000,
    stock: 26,
    volume: '150 мл',
    description: 'Масло для первого этапа вечернего очищения.',
  ),
]);

final seedSuppliers = [
  Supplier(
    id: 1,
    name: 'Дерма Косметик',
    city: 'Москва',
    email: 'derma@example.com',
    phone: '+7 900 100-10-01',
    brandIds: [1, 7, 8],
  ),
  Supplier(
    id: 2,
    name: 'Бьюти Дистрибьюшн',
    city: 'Санкт-Петербург',
    email: 'beauty@example.com',
    phone: '+7 900 100-10-02',
    brandIds: [2, 4, 5, 6],
  ),
  Supplier(
    id: 3,
    name: 'Корея Бьюти',
    city: 'Казань',
    email: 'korea@example.com',
    phone: '+7 900 100-10-03',
    brandIds: [3],
  ),
];
final seedCustomers = [
  for (var i = 1; i <= 12; i++)
    Customer(
      id: i,
      name: [
        'Анна Смирнова',
        'Мария Иванова',
        'Елена Петрова',
        'Ольга Соколова',
        'Дарья Кузнецова',
        'Софья Попова',
        'Ирина Новикова',
        'Алина Морозова',
        'Екатерина Волкова',
        'Полина Фёдорова',
        'Юлия Орлова',
        'Виктория Васильева',
      ][i - 1],
      email: 'customer$i@example.com',
      phone: '+7 900 200-${i.toString().padLeft(4, '0')}',
      card: LoyaltyCard(
        id: i,
        number: 'LC-${i.toString().padLeft(6, '0')}',
        issuedAt: DateTime(2026, 1, 15),
        expiresAt: DateTime(2029, 1, 15),
        points: i * 100,
      ),
    ),
];
